<a href="https://colab.research.google.com/github/M-8-ops/WEEK-2-PROJECT-MODEL-COMPARISON/blob/main/multiple_linear_regression_for_LuxAcad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('MOCK_DATA (8).csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['New York' 1971]
 ['Los Angeles' 1316]
 ['Los Angeles' 2273]
 ...
 ['New York' 1702]
 ['Los Angeles' 1656]
 ['New York' 1392]]


Encoding the Categorical Data


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)

[[0.0 0.0 1.0 1971]
 [0.0 1.0 0.0 1316]
 [0.0 1.0 0.0 2273]
 ...
 [0.0 0.0 1.0 1702]
 [0.0 1.0 0.0 1656]
 [0.0 0.0 1.0 1392]]


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
print(X_train)

[[0.0 1.0 0.0 1296]
 [0.0 1.0 0.0 2722]
 [1.0 0.0 0.0 1081]
 ...
 [1.0 0.0 0.0 1782]
 [0.0 0.0 1.0 2907]
 [0.0 0.0 1.0 508]]


In [11]:
print(y_train)

[560.16 826.3  476.99 530.79 823.54 919.88 312.42 631.25 887.43 285.78
 539.94 753.35 511.14 418.34 787.08 577.22 808.46 463.79 325.95 138.47
 645.02 427.39 957.59 729.94 730.52 497.74 220.76 350.05 620.4  269.97
 904.85 380.66 756.58 421.24 544.71 263.27 854.7   99.87 482.03 499.53
  58.83 432.13  62.69 993.18 981.25 509.98 797.14 563.59 800.61 811.41
 273.68 238.97 260.56 553.8  849.88 143.64 281.27 787.68 572.89 720.35
 191.34 594.35 214.11 551.9  419.2  589.36 271.37 645.61 437.44 518.66
 859.83 132.72 980.23 120.41 461.65 193.89 760.67 969.04 646.25 863.52
 174.94 204.87 635.77 164.38 153.8  407.58 647.92 849.54 267.17 280.25
 259.95 966.33 376.43 511.09 549.82 456.98 514.28 425.12 560.52 274.65
 656.78 950.08 291.9  203.11 143.42 621.47 342.52 644.61 323.23 622.79
 694.2  372.22  64.8  867.91 373.94 532.77 742.84 571.19 897.57 141.06
 178.42 870.8  539.97 707.   825.31 639.3  894.22 516.61 879.05 668.74
 127.26 478.84 854.32 114.55 416.15 794.92 117.95 560.83 156.59 228.88
 520.6

FEATURE SCALING

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:] = sc.fit_transform(X_train[:, 1:])
X_test[:, 1:] = sc.transform(X_test[:, 1:])


In [17]:
print(X_train)

[[0.0 1.4128887718599612 -0.7157425057893192 -0.6747419445519529]
 [0.0 1.4128887718599612 -0.7157425057893192 1.311800871451113]
 [1.0 -0.7077697975358527 -0.7157425057893192 -0.9742557632340421]
 ...
 [1.0 -0.7077697975358527 -0.7157425057893192 0.0022985944224438665]
 [0.0 -0.7077697975358527 1.397150500230811 1.569522064270585]
 [0.0 -0.7077697975358527 1.397150500230811 -1.7724949172100282]]


## Training the Multiple Linear Regression model on the Training set

In [18]:
from sklearn.linear_model import LinearRegression
#we build the model
regressor = LinearRegression()
#Then train the model on the training set
regressor.fit(X_train,y_train)

LinearRegression()

## Predicting the Test set results

In [19]:
y_predict = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))

[[536.   518.35]
 [500.5  666.39]
 [516.   954.74]
 [501.   425.52]
 [515.5  700.96]
 [515.   860.23]
 [500.5  518.16]
 [536.75 234.55]
 [514.5  696.26]
 [536.75 914.77]
 [499.75 999.15]
 [515.5  260.33]
 [516.5  507.71]
 [499.75 949.54]
 [516.   263.81]
 [536.75 899.08]
 [536.   209.  ]
 [501.   463.4 ]
 [537.5  323.78]
 [499.5  287.53]
 [515.   377.74]
 [516.    89.89]
 [536.5  730.04]
 [500.   498.42]
 [516.   979.25]
 [537.25 801.3 ]
 [515.   748.58]
 [514.5   82.47]
 [536.25 503.08]
 [515.   969.33]
 [515.5  704.08]
 [500.5  804.89]
 [500.25 996.85]
 [515.5  238.18]
 [500.25 408.81]
 [515.5  734.67]
 [516.   624.03]
 [500.75 143.41]
 [501.    99.29]
 [500.   350.95]
 [500.5  104.04]
 [536.25 387.87]
 [515.5  717.38]
 [499.75 705.29]
 [501.   974.3 ]
 [500.   942.42]
 [499.5  656.99]
 [500.25 960.47]
 [536.75 600.62]
 [516.   799.95]
 [536.5  194.44]
 [536.   304.69]
 [501.   235.6 ]
 [536.   387.23]
 [514.5  437.84]
 [516.   677.89]
 [536.5  317.81]
 [516.   156.75]
 [516.5  933.5

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)

-0.005964138993396428